// types/pmc_research.ts

// Response from starting a PMC research task
export interface StartPmcResearchResponse {
  task_id: string
  message?: string
}

// Response when checking the status of a PMC research task
export interface PmcResearchStatusResponse {
  task_id: string
  status: 'pending' | 'processing' | 'completed' | 'failed'
  message?: string
  progress?: number // Optional: progress 0-100
}

// Structure for individual articles found during PMC research
export interface PmcResearchArticle {
  id: string // Or another unique identifier
  title: string
  url?: string
  summary?: string
  // Add other relevant fields from your API (e.g., authors, journal, year)
}

// Response containing the final results of a completed PMC research task
export interface PmcResearchResultResponse {
  task_id: string
  status: 'completed' // Or the final status indicating success
  query: string // The original query that initiated the research
  summary?: string // Optional summary generated by the backend
  markdown_report?: string // Optional detailed report in Markdown format
  articles?: PmcResearchArticle[] // Optional list of found articles
  message?: string // Optional overall message accompanying the results
}

// Add other PMC research-related types if needed
