import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowLeft, FileText, Scale, AlertTriangle, ShieldCheck } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Terms of Service | Morphic AI',
  description: 'Terms of Service for Morphic AI search application and services.'
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground antialiased selection:bg-primary selection:text-primary-foreground">
      {/* Navigation Header */}
      <header className="sticky top-0 z-40 w-full border-b border-border/80 bg-background/80 backdrop-blur-md py-4 px-6">
        <div className="mx-auto flex max-w-5xl items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Link>
          <div className="flex items-center gap-2">
            <Scale className="h-5 w-5 text-primary" />
            <span className="text-sm font-semibold tracking-tight">Terms of Service</span>
          </div>
        </div>
      </header>

      {/* Main Legal Content */}
      <main className="mx-auto max-w-4xl px-4 sm:px-6 py-12 sm:py-20">
        <article className="prose dark:prose-invert max-w-none space-y-8">
          <div className="border-b border-border pb-8">
            <h1 className="text-3xl sm:text-5xl font-bold tracking-tight text-foreground">
              Terms of Service
            </h1>
            <p className="mt-3 text-sm text-muted-foreground">
              Effective Date: January 1, 2026 | Last Updated: July 2026
            </p>
          </div>

          <p className="text-base leading-relaxed text-muted-foreground">
            Welcome to <strong>Morphic AI</strong>! These Terms of Service (&quot;Terms&quot;, &quot;Agreement&quot;) govern your access to and use of the website located at <code className="text-xs bg-muted px-1.5 py-0.5 rounded">ai-morphic.vercel.app</code> and all associated web services provided by Morphic AI.
          </p>

          <hr className="border-border my-8" />

          {/* Terms Section 1 */}
          <section className="space-y-4">
            <h2 className="text-xl sm:text-2xl font-semibold text-foreground flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" /> 1. Acceptance of Terms
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              By accessing or using Morphic AI, you agree to be bound by these Terms. If you disagree with any part of these terms, you may not access or use our services.
            </p>
          </section>

          {/* Terms Section 2 */}
          <section className="space-y-4">
            <h2 className="text-xl sm:text-2xl font-semibold text-foreground flex items-center gap-2">
              <ShieldCheck className="h-5 w-5 text-primary" /> 2. Description of Service
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Morphic AI provides an open-source, generative web intelligence engine that synthesizes live web data into answers with verifiable inline primary citations and dynamic UI components.
            </p>
          </section>

          {/* Terms Section 3 */}
          <section className="space-y-4">
            <h2 className="text-xl sm:text-2xl font-semibold text-foreground flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-primary" /> 3. Acceptable Use Policy
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              You agree not to misuse the Morphic AI service. Specifically, you agree not to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-sm text-muted-foreground">
              <li>Use the service for any illegal, unauthorized, or prohibited purpose under applicable laws.</li>
              <li>Attempt to disrupt, breach, rate-limit overload, or disable the search engine infrastructure.</li>
              <li>Scrape or automatedly query the backend APIs without adherence to standard web conventions.</li>
            </ul>
          </section>

          {/* Terms Section 4 */}
          <section className="space-y-4">
            <h2 className="text-xl sm:text-2xl font-semibold text-foreground">
              4. Disclaimer of Warranties & Limitation of Liability
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              The service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. Morphic AI explicitly disclaims all warranties of any kind, whether express or implied. Search results generated by Large Language Models (LLMs) and real-time synthesis should be cross-verified using the provided primary sources.
            </p>
          </section>

          {/* Terms Section 5 */}
          <section className="space-y-4">
            <h2 className="text-xl sm:text-2xl font-semibold text-foreground">
              5. Open Source License & Intellectual Property
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Morphic AI is distributed under the open-source MIT License. You are free to inspect, fork, deploy, or modify the repository in accordance with the terms of the MIT License.
            </p>
          </section>

          <div className="border-t border-border pt-8 mt-12">
            <h2 className="text-lg font-semibold text-foreground">Contact Us</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              If you have any questions regarding these Terms, please contact us through our official project repository on GitHub.
            </p>
          </div>
        </article>
      </main>
    </div>
  )
}
