import type { ComponentType, SVGProps } from 'react'

import {
  ArrowLeft,
  Attachment,
  BookStack,
  ChatBubble,
  Check,
  CheckCircle,
  Clock,
  Compass,
  Copy,
  EditPencil,
  GitCompare,
  Globe,
  HalfMoon,
  HelpCircle,
  Home,
  InfoCircle,
  JournalPage,
  Laptop,
  Link as LinkIcon,
  LogIn,
  LogOut,
  Map as MapIcon,
  MapPin,
  MapsArrow,
  Message,
  MoreHoriz,
  NavArrowDown,
  OpenNewWindow,
  Page,
  Palette,
  Plus,
  Refresh,
  Ruler,
  Search,
  Send,
  Settings,
  ShareIos,
  SidebarCollapse,
  SidebarExpand,
  Square,
  SunLight,
  Trash,
  Upload,
  UserCircle,
  WarningTriangle,
  Xmark,
  XmarkCircle
} from 'iconoir-react'

import { IconLogoOutline } from '@/components/ui/icons'

export type NativeIconComponent = ComponentType<SVGProps<SVGSVGElement>>

export const nativeIconMap = {
  account: UserCircle,
  arrowLeft: ArrowLeft,
  attachment: Attachment,
  bot: ChatBubble,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: NavArrowDown,
  clock: Clock,
  close: Xmark,
  closeCircle: XmarkCircle,
  compare: GitCompare,
  compass: Compass,
  copy: Copy,
  discover: Globe,
  error: XmarkCircle,
  explain: HelpCircle,
  externalLink: OpenNewWindow,
  feedback: EditPencil,
  home: Home,
  info: InfoCircle,
  latest: JournalPage,
  library: BookStack,
  link: LinkIcon,
  login: LogIn,
  logout: LogOut,
  map: MapIcon,
  mapPin: MapPin,
  message: Message,
  moreHoriz: MoreHoriz,
  navigation: MapsArrow,
  newChat: Plus,
  refresh: Refresh,
  research: Search,
  ruler: Ruler,
  scrollDown: NavArrowDown,
  search: Search,
  send: Send,
  settings: Settings,
  share: ShareIos,
  sidebarClosed: SidebarExpand,
  sidebarOpen: SidebarCollapse,
  stop: Square,
  summarize: Page,
  theme: Palette,
  themeDark: HalfMoon,
  themeLight: SunLight,
  themeSystem: Laptop,
  trash: Trash,
  upload: Upload,
  warning: WarningTriangle,
  adaptive: IconLogoOutline
} satisfies Record<string, NativeIconComponent>

export type NativeIconName = keyof typeof nativeIconMap
